name: english_quiz
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  flutter_dotenv: ^3.1.0
  flutter_bloc: ^7.0.0
  path_provider: ^2.0.1
  keyboard_dismisser: ^1.0.2
  community_material_icon: ^5.9.55
  cached_network_image: ^2.1.0+1
  carousel_slider: ^3.0.0
  permission_handler: ^4.4.0+hotfix.2
  get: ^4.0.3
  grouped_list: ^3.7.1
  formz: ^0.4.0-nullsafety.0
  equatable: ^2.0.0
  intl: ^0.17.0
  webview_flutter: ^2.0.4
  toggle_switch: ^0.1.9
  font_awesome_flutter: ^9.0.0
  image_picker: ^0.6.2+3
  double_back_to_close_app: ^2.0.1
  pull_to_refresh: ^1.6.4
  url_launcher: ^6.0.3
  device_info: ^2.0.2
  bubble_tab_indicator: ^0.1.4
  utils_libs:
    path: utils_libs
  change_app_package_name: ^1.0.0
  animated_drawer: ^0.0.4
  pie_chart: ^5.0.0
  shared_preferences: ^2.0.5
  flutter_plugin_android_lifecycle: ^2.0.2
  modal_bottom_sheet: ^2.0.0
  html_unescape: ^2.0.0
  flutter_custom_clippers: ^2.0.0
  auto_size_text: ^2.1.0
  quiver: ^3.0.1
  flutter_widget_from_html_core: ^0.6.2
  expandable_text: ^2.2.0
  flutter_inappwebview: ^5.3.2
  pdf: ^3.6.0
  flutter_pdfview: ^1.0.0+10

#dependency_overrides:
#  sqflite: 2.0.0+3

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto_Regular.ttf
          weight: 400
        - asset: assets/fonts/Roboto_Italic.ttf
          style: italic
        - asset: assets/fonts/Roboto_Bold.ttf
          weight: 900
  assets:
    - assets/.env
    - assets/lottie/
    - assets/images/
    - assets/fonts/
    - assets/icons/
