name: utils_libs
description: libs Washing machine

environment:
  sdk: '>=2.7.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  intl: ^0.17.0
  lottie: ^1.2.1
  get: ^4.3.8
  shared_preferences: ^2.0.8
  json_annotation: ^4.3.0
  equatable: ^2.0.3
  retrofit: ^2.2.0
  dio: ^4.0.1
  formz: ^0.4.1

  meta:

dev_dependencies:
  mockito:
  flutter_test:
    sdk: flutter
  build_runner: ^2.1.5
  json_serializable: ^6.0.1
  retrofit_generator: ^2.2.0
